### ISSUE TITLE
Function Finder Master Checklist

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/function-finder#1]
## Design
- [ ] **Sim folder and design doc created** (Date: //) 
  - [ ] Create sim folder in [PhET Sim Design Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYUUhvZnlCUDF0bGc) using phet-docs account
  - [ ] Place design doc in the sim folder
- [ ] **Learning goals and standards identified** (Date: //)
- [ ] **Design concept complete**  (Date: //)
- [ ] **Wireframes complete** (Date: //) 
- [ ] **Mockups complete** (Date: //) 
  - [ ] Mockups checked for colorblind and greyscale
- [ ] **Features for PhET-iO discussion** 
- [ ] **Interviews complete** (Date: //) 
  - [ ] Results reported to team
  - [ ] Notes pasted into design doc
  - [ ] Back-up of interviews
- [ ] **Lead designer "sign off"** (Date: //) 
  - [ ] Performance acceptable
  - [ ] Carefully review ?showPointerAreas
  - [ ] No new feature requests
- [ ] **Pre-publication items** 
  - [ ] Main screenshot (2048x1344, PNG, 32-bit color, browser chrome stripped)
  - [ ] Auxilary screenshots (up to 3 additional)
  - [ ] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [ ] Teacher Guide
  - [ ] Add an activity
  - [ ] Sim primer draft
  - [ ] Verify credits
- [ ] **Post-publication items** 
  - [ ] Add to Edmodo
  - [ ] Add to [Gooru](http://gooru.org/PhET/content/resources) (signed in as phethelp)
  - [ ] Sim primer (create issue, publish ideally within 1 month of live sim)
  - [ ] Hold postmortem if applicable (Date: //) 

## Implementation
- [ ] **Sim repo created** (Date: //) 
  - [ ] Simula-rasa used to create basic project structure
  - [ ] Grunt unpublished-readme run to create the initial readme file
  - [ ] Collaborators added (such as QA team, designers, etc)
  - [ ] Standard label set applied
  - [ ] Sim added to active repos list in chipper
  - [ ] Sim suggestions doc reviewed
- [ ] **Initial development started** (Date: //)
- [ ] **Sim feature complete** (Date: //) 
- [ ] **Code review complete** (Date: //) 
  - [ ] Code review checklist
  - [ ] Model description 
- [ ] **Published** (Date: //) 
  - [ ] Update repo README to published template (in master and release branch)
 

## QA
- [ ] **Dev testing complete** (Date: //) 
- [ ] **First release candidate** (Date: //)
  - [ ] Place matrix in [Testing Matrices Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYbW9fTGNCODdYVjQ)
  - [ ] Test matrix deemed complete
